### PR TITLE
Fix index-fn reexport collisions

### PR DESCRIPTION
**Pull request by sgomes**
This PR renames some re-exports in `index-fn.js`, so that there are no name collisions.

See #171.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you so much! I don't think we need these exports at all, the whole point of `index-fn` is to be tree-shakeable and `register()` is used to add these methods to the `Color` object (see how it's used in `index.js`). So I think we can just remove these exports, do you agree?

**Comment by LeaVerou** [comment]
Oops, didn't mean to close this, sorry! (puzzled how Cmd + enter did that)

**Comment by sgomes** [comment]
> So I think we can just remove these exports, do you agree?

@LeaVerou Yes, that sounds good! Done 🙂

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
Thanks, just did so! I guess I'll wait an hour or so before other low hanging fruit emerges

**Comment by LeaVerou** [comment]
Actually scratch that, if people are playing with it, we shouldn't have a broken package. I've merged all open PRs and will release now.

**Pull request merged**
