### PR TITLE
Accept "Lightness" for lab space first channel name.

### LINKED ISSUE #345: Lab spaces (lab, lab-d65, and oklab) should accept `Lightness` in addition to `L` for first coordinate name.
Most spaces accept full spelled out versions of coordinate names as the `coordId`, but the three Lab spaces only accept `L` and not `Lightness`.

```js
const color = new Color("red");
console.log(color.lch.lightness); // 54.3
console.log(color.lab.l); // 54.3
console.log(color.lab.lightness); // throws error
```

@LeaVerou Was this an intentional design decision? I can't find anything in the spec that would warrant this. If it wasn't intentional, I'm happy to submit a PR.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
Fixes #345

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks for working on this! I'll defer to @svgeesus on this one

**Comment by jgerigmeyer** [comment]
@LeaVerou Now that @svgeesus [approved this in theory](https://github.com/LeaVerou/color.js/issues/345#issuecomment-1813201428), are there additional changes that need to be made to update the channel accessors here, or can this be merged?

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
If it doesn't cause any breaking changes, LGTM!

**Comment by jgerigmeyer** [comment]
> If it doesn't cause any breaking changes, LGTM!

No breaking changes, the existing `l` accessor will still work 👍

**Pull request merged**
