### PR TITLE
Allow to extend the deltaE methods

### PR DESCRIPTION
**Pull request by latin-1**
```js
Color.deltaEMethods.deltaECustom = (color, sample) => { ... };
color1.deltaE(color2, {method: "custom"});
```

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, sorry for the delay but we just hadn't gotten to this, it's not that we were against it! Could you please reopen?

**Comment by latin-1** [comment]
I simply forgot I had this PR open 🤣

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Good job spotting the issue that the deltaE methods cannot be extended right now! We definitely need to fix this.
However, this way would only work for the OO API, and not the procedural one.
I'd prefer to find a different solution, possibly an exported object from `deltaE/index.js` that people would add their methods to?

**Comment by latin-1** [comment]
Closing in favor of #280

**Pull request closed without merging**
