### PR TITLE
Update outdated wiki links in README.md

### PR DESCRIPTION
**Pull request by MysteryBlokHed**
Changes a couple of documentation links in the README that use relative links instead of links to the website.

### CODE REVIEW

**Comment by LeaVerou** [comment]
What if we use links that start with `/`? I'd rather avoid absolute links if possible.

**Comment by MysteryBlokHed** [comment]
I could change the links to point to the repository’s `.md` files in the docs folder, if that’s preferred? i.e.:

```diff
- **Doesn't gloss over color science**: Actual <a href="docs/gamut-mapping.html">gamut mapping</a> instead of naïve clipping,
+ **Doesn't gloss over color science**: Actual <a href="docs/gamut-mapping.md">gamut mapping</a> instead of naïve clipping,
```

**Comment by LeaVerou** [comment]
Wouldn't that make them point to `.md` files in the website as well?

**Comment by MysteryBlokHed** [comment]
Does the built documentation include the main README file? If it does, then I’m not sure if there’s any way to make relative links work properly, since they’d have to go to `.md` files on the repository, and `.html` files on the website.

It might be possible to use relative links if the website redirected URLs ending in `.md` to `.html`?

**Comment by Myndex** [comment]
> Wouldn't that make them point to `.md` files in the website as well?

If _no_ extension is put on the file name, then the HTML server should serve the file with the .html, and GitHub will serve the file with .md, so 

`docs/gamut-mapping` 

Should work for both, it does on the Jekyll-built sites I'm hosting here, and for colorjs would seem just a matter of configuring Eleventy to use the extension that Apache is configured for (i.e. htm or html or php or whatever)

**Comment by LeaVerou** [comment]
Some ways to address this:
- We could instead follow the convention of having `README.md` in its own folder, compiled to `index.html` and just point links to folders (with trailing `/`)
- We could add Netlify redirects that rewrite `foo.md` to `foo/index.html`, but that means we now have no way to actually request MD files (which may be ok?)

**Comment by Myndex** [comment]
I don't know Netifly, but it is seamless with Jekyll.

All my files use .md and Jekyll turns all the .md into .html to serve (with the code inside also being converted of course). The way the GitHub pages server is setup here (and the way my own Apache servers are setup other places) only the file name, with no extension, is needed, and in the case of multiple file names with different extensions, the conf file lists the priority order.

E.g.` .php, .htm, .html, .txt ... `

All the _links_ in my pages, or in other pages linking here, therefore do not have an extension at all on them, and the server(s) determine which to serve per context.

**_So this:_**
https://myndex.github.io/colorparsley/versionHistory

**_Is automatically displaying this, without displaying the extension:_**
https://myndex.github.io/colorparsley/versionHistory.html

But if you add .md
https://myndex.github.io/colorparsley/versionHistory.md

Then you still get the unparsed markdown file raw.... 

Which you may or may not want, but you may want to access your .txt or other files from the web interface, which is possible at least in the GitHub environment. My point being that you don't need a single file in a folder trick, because you don't need extensions on _any_ URL used as a link, the way Jekyll-build pages are configured.

For the server, it's trivial to setup in Apache. I have to think that Netifly could be so configured to do it's voodoo similarly...

**Pull request closed without merging**
