### PR TITLE
[apps/convert] fix issue #123

### PR DESCRIPTION
**Pull request by Mohammed785**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thank you for working on this!

However, UX wise I don't think this is a good solution.
1. It is quite surprising to overwrite the user's clipboard just because they clicked on a color format. Writing on the user's clipboard should always be opt-in, through UI that clearly indicates what it does.
2. It still doesn't solve the actual UI problem which is that colors cannot be selected with the mouse without actually clicking on them.

cc @smfr @svgeesus for input

**Review by LeaVerou — CHANGES_REQUESTED** [review]
See comments

**Comment by Mohammed785** [comment]
please review the new updates

**Comment by svgeesus** [comment]
#123 has been closed, meanwhile, so closing this PR

**Pull request closed without merging**
