### PR TITLE
Add Carbon

### PR DESCRIPTION
**Pull request by sayzlim**
This is a new PR with the same purpose as this PR: https://github.com/LeaVerou/color.js/pull/195

### CODE REVIEW

**Comment by sayzlim** [comment]
@LeaVerou this one should be okay now. Please review and let me know if I need to change anything else.

**Comment by LeaVerou** [comment]
Hi @sayzlim, thank you! I think I would prefer it closer to the right side of the viewport on large screens, rather than right next to the content. Would you be able to make this change?

**Comment by sayzlim** [comment]
@LeaVerou all set! Please review again.

**Comment by LeaVerou** [comment]
Fantastic, thank you!

**Pull request merged**
