### PR TITLE
Add Carbon Ads

### PR DESCRIPTION
**Pull request by sayzlim**
Integrate Carbon into the project. [Here is the screenshots placement](https://dropover.cloud/0fe76c) on desktop and mobile.

Some considerations:
- The ad will stay fixed on the right side of the content for viewport > 1280px.
- The ad will be visible before the footer when the viewport is < 1280px to ensure that site content remains the main focus of the site.

@LeaVerou feel free to review when it's convenient to you. I'm not sure whether the CSS has been added to the right file because I'm not familiar with how PostCSS works. Let me know if there is any changes I can make to make this integration better.

Thanks!

### CODE REVIEW

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Hi there, could you take a look at the deploy preview? It doesn't look right.

**Comment by sayzlim** [comment]
@LeaVerou looks like I added CSS to the wrong file. Just made a change and rebuild them. The preview should be correct this time.

**Comment by sayzlim** [comment]
I'm not sure why there are 35 files have been updated. I tried to sync to the latest update. Do I need to refork again? Let me know if that's the best option.

**Comment by sayzlim** [comment]
Hey @LeaVerou, I'm going to close this pull request and make a new one. It's a bit messy to review at this state. Will let you know when the new PR is ready.

**Pull request closed without merging**
